# ifdef SERVO_COMMAND_H
# define SERVO_COMMAND_H

enum SERVO_COMMAND {
    SET_SERVO_SYNC_MODE = 0,
    START_SERVO_SYNC = 1,
    ALLOW_PWM_PULSE_OUTPUT = 2,
    SET_SERVO_TARGET_BY_PULSE_WIDTH = 3,
    SET_SERVO_TARGET_BY_RECTANGLE = 4,
    GET_SERVO_POSITION_BY_PULSE_WIDTH = 5,
    GET_SERVO_POSITION_BY_RECTANGLE = 6
};

# endif