# ifdef SERVO_CHANNEL_H
# define SERVO_CHANNEL_H

enum SERVO_CHANNEL {
    RIGHT_HAND_CHANNEL = 0,
    RIGHT_FOOT_HORIZONTAL_CHANNEL = 1,
    RIGHT_FOOT_VERTICAL_CHANNEL = 2,
    NECK_CHANNEL = 3,
    LEFT_FOOT_VERTICAL_CHANNEL = 4,
    LEFT_FOOT_HORIZONTAL_CHANNEL = 5,
    LEFT_HAND_CHANNEL = 6
};

# endif